/*
 * Copyright (c) 2021 独角鲸 Inc. All rights reserved.
 */

package com.apemans.smartipcimpl.db

/***********************************************************
 * 作者: zhengruidong@apemans.com
 * 日期: 2021/9/15 5:09 下午
 * 说明:
 *
 * 备注:
 *
 ***********************************************************/

const val KEY_UID = "KEY_UID";
const val KEY_DEVICE_ID = "KEY_DEVICE_ID";
const val KEY_DEVICE_MODEL = "KEY_DEVICE_MODEL";
const val KEY_DEVICE_NAME = "KEY_DEVICE_NAME";
const val KEY_DEVICE_MAIN_CATEGORY = "KEY_DEVICE_MAIN_CATEGORY";
const val KEY_DEVICE_SUB_CATEGORY = "KEY_DEVICE_SUB_CATEGORY";
const val KEY_DEVICE_PLATFORM = "KEY_DEVICE_PLATFORM";
const val KEY_DEVICE_ICON_URL = "KEY_DEVICE_ICON_URL";
const val KEY_DEVICE_BRAND = "KEY_DEVICE_BRAND";
const val KEY_DEVICE_COMMUNICATION_TYPE = "KEY_DEVICE_COMMUNICATION_TYPE";
const val KEY_DEVICE_BIND_TYPE = "KEY_DEVICE_BIND_TYPE";
const val KEY_DEVICE_SN = "KEY_DEVICE_SN";
const val KEY_DEVICE_MAC = "KEY_DEVICE_MAC";
const val KEY_DEVICE_VERSION = "KEY_DEVICE_VERSION";
const val KEY_DEVICE_LOCAL_IP = "KEY_DEVICE_LOCAL_IP";
const val KEY_DEVICE_WAN_IP = "KEY_DEVICE_WAN_IP";
const val KEY_DEVICE_TIME = "KEY_DEVICE_TIME";
const val KEY_DEVICE_HB_SERVER = "KEY_DEVICE_HB_SERVER";
const val KEY_DEVICE_HB_PORT = "KEY_DEVICE_HB_PORT";
const val KEY_DEVICE_HB_DOMAIN = "KEY_DEVICE_HB_DOMAIN";
const val KEY_DEVICE_OPEN_STATUS = "KEY_DEVICE_OPEN_STATUS";
const val KEY_DEVICE_ONLINE = "KEY_DEVICE_ONLINE";
const val KEY_DEVICE_ZONE = "KEY_DEVICE_ZONE";
const val KEY_DEVICE_IS_GOOGLE = "KEY_DEVICE_IS_GOOGLE";
const val KEY_DEVICE_IS_ALEXA = "KEY_DEVICE_IS_ALEXA";
const val KEY_DEVICE_P_DEVICE_ID = "KEY_DEVICE_P_DEVICE_ID";
const val KEY_DEVICE_WIFI_LEVEL = "KEY_DEVICE_WIFI_LEVEL";
const val KEY_DEVICE_BATTERY_LEVEL = "KEY_DEVICE_BATTERY_LEVEL";
const val KEY_DEVICE_SORT = "KEY_DEVICE_SORT";
const val KEY_DEVICE_P_MODEL = "KEY_DEVICE_P_MODEL";
const val KEY_DEVICE_P_VERSION = "KEY_DEVICE_P_VERSION";
const val KEY_DEVICE_MODEL_TYPE = "KEY_DEVICE_MODEL_TYPE";
const val KEY_DEVICE_SECRET = "KEY_DEVICE_SECRET";
const val KEY_DEVICE_IS_THEFT = "KEY_DEVICE_IS_THEFT";
const val KEY_DEVICE_IS_NOTICE = "KEY_DEVICE_IS_NOTICE";
const val KEY_DEVICE_APP_TIME_CONFIG = "KEY_DEVICE_APP_TIME_CONFIG";
const val KEY_DEVICE_MQTT_ONLINE = "KEY_DEVICE_MQTT_ONLINE";
const val KEY_DEVICE_REGION = "KEY_DEVICE_REGION";
const val KEY_DEVICE_BLE_DEVICE_ID= "KEY_DEVICE_BLE_DEVICE_ID";
const val KEY_DEVICE_SSID = "KEY_DEVICE_SSID";
const val KEY_DEVICE_OWNER_ACCOUNT = "KEY_DEVICE_OWNER_ACCOUNT";
const val KEY_DEVICE_OWNER_NICKNAME = "KEY_DEVICE_OWNER_NICKNAME";
