package com.apemans.smartipcimpl.constants

/**
 * @author Dylan Cai
 */


const val KEY_HOME_ID = "home_id"
const val KEY_MEMBER_ID = "member_id"
const val KEY_NICKNAME = "nickname"
const val KEY_ACCOUNT = "account"
const val KEY_IS_OWNER = "is_owner"
const val KEY_EMAIL = "email"
const val KEY_URL = "url"
const val KEY_TYPE = "type"
const val KEY_SSID = "ssid"
const val KEY_PSD = "psd"

const val KEY_DEVICE_ID = "device_id"
const val KEY_DEVICE_MODEL = "device_model"
const val KEY_DEVICE_NAME = "device_name"

const val KEY_CLOUD_PACK_PARAM_UUID = "uuid"
const val KEY_CLOUD_PACK_PARAM_MODEL = "model"
const val KEY_CLOUD_PACK_PARAM_ENTER_MARK = "enter_mark"
const val KEY_CLOUD_PACK_PARAM_ORIGIN = "origin"


const val IPC_DEVICE_INFO = "IpcDeviceInfo"
const val INTENT_KEY_DETECTION_TYPE = "INTENT_KEY_DETECTION_TYPE"
const val INTENT_KEY_DEVICE_ID = "INTENT_KEY_DEVICE_ID"
const val INTENT_KEY_PARENT_DEVICE_ID = "INTENT_KEY_PARENT_DEVICE_ID"
const val INTENT_KEY_MODEL = "INTENT_KEY_MODEL"
const val INTENT_KEY_BIND_TYPE = "INTENT_KEY_BIND_TYPE"
const val INTENT_KEY_DEVICE_NAME = "INTENT_KEY_DEVICE_NAME"
const val INTENT_KEY_DEVICE_SSID = "INTENT_KEY_DEVICE_SSID"
const val INTENT_KEY_DEVICE_PASSWORD = "INTENT_KEY_DEVICE_PASSWORD"
const val INTENT_KEY_DEVICE_ONLINE_STATE = "INTENT_KEY_DEVICE_ONLINE_STATE"
const val INTENT_KEY_DETECTION_SCHEDULE_ID = "INTENT_KEY_DETECTION_SCHEDULE_ID"
const val INTENT_KEY_START_TIME = "INTENT_KEY_START_TIME"
const val INTENT_KEY_END_TIME = "INTENT_KEY_END_TIME"
const val INTENT_KEY_WEEK_ARR = "INTENT_KEY_END_WEEK_ARR"
const val INTENT_KEY_OPERATION_TYPE = "INTENT_KEY_OPERATION_TYPE"
const val INTENT_KEY_DATA_PARAM_1 = "INTENT_KEY_DATA_PARAM_1"


/**
 * IPC跳转参数
 */
const val INTENT_KEY_IPC_MODEL = "IPC_MODEL"
const val INTENT_KEY_CONNECTION_MODE = "INTENT_KEY_CONNECTION_MODE"
const val INTENT_KEY_SSID = "INTENT_KEY_SSID"
const val INTENT_KEY_ROUTE_SOURCE = "INTENT_KEY_ROUTE_SOURCE"
const val INTENT_KEY_START = "INTENT_KEY_START"
const val INTENT_KEY_TIME_STAMP = "INTENT_KEY_TIME_STAMP"
const val INTENT_KEY_DATA_TYPE = "INTENT_KEY_DATA_TYPE"
const val INTENT_KEY_PLAYER_NAME = "INTENT_KEY_PLAYER_NAME"
const val INTENT_KEY_PLAYER_BIND_TYPE = "INTENT_KEY_PLAYER_BIND_TYPE"
const val INTENT_KEY_PARENT_DEVICEID = "INTENT_KEY_PARENT_DEVICEID"

const val DETECTION_TYPE_MOTION = 1
const val DETECTION_TYPE_SOUND = 2
const val DETECTION_TYPE_HUMAN = 3

const val MEDIA_MODE_OPERATION_TYPE_MODE= 1
const val MEDIA_MODE_OPERATION_TYPE_IMAGE_NUM = 2
const val MEDIA_MODE_OPERATION_TYPE_DURATION = 3

const val DETECTION_AREA_OPERATION_TYPE_SWITCH = 1
const val DETECTION_AREA_OPERATION_TYPE_CONFIGURE = 2

const val HOUR_LENGTH_OF_DAY = 24
const val MIN_LENGTH_OF_HOUR = 60
const val SECOND_LENGTH_OF_MIN = 60
const val WEEK_DAY_LENGTH = 7
const val DETECTION_PLAN_SCHEDULE_SIZE = 3

const val DEVICE_BIND_TYPE_OWNER = "OWNER"
const val DEVICE_BIND_TYPE_SHARER = "SHARER"

//视图回调状况码
const val VD_ACTION_IPC_DETECTION_SCHEDULE_ITEM_SWITCH = 1

const val THIRD_PARTY_CONTROL_PARENT_URL = "file:///android_asset/html/thirdpartycontrol/"
const val THIRD_PARTY_CONTROL_ALEXA_PATH = "alexa.html"
const val THIRD_PARTY_CONTROL_GOOGLE_ASSISTANT_PATH = "google.html"


const val GESTURE_MOVE_LEFT = 1
const val GESTURE_MOVE_TOP = 2
const val GESTURE_MOVE_RIGHT = 3
const val GESTURE_MOVE_BOTTOM = 4
const val GESTURE_TOUCH_DOWN = 5
const val GESTURE_TOUCH_UP = 6

const val ONLINE_STATUS_OFF = 0
const val ONLINE_STATUS_ON = 1

const val ACTIVITY_PATH_GOTO_HYBRID_WEB_VIEW = "/message/hybrid_web_view"

/**
 * 方位图片个数
 */
const val PRESET_POINT_MAX_LEN = 3
const val PRESET_POINT_FIRST_POSITION = 1